name: Publish package to GitHub Packages

on:
  push:
    branches: 
      - '[1-9]*.[0-9]*.[0-9]*'

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate settings.xml
        run: |
          cat << EOF > settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.MAVEN_PACKAGES_USERNAME }}</username>
                <password>${{ secrets.MAVEN_PACKAGES_PASSWORD }}</password>
              </server>
            </servers>

            <profiles>
              <profile>
                <id>github-packages</id>
                <activation>
                  <activeByDefault>true</activeByDefault>
                </activation>
                <repositories>
                  <repository>
                    <id>github</id>
                    <name>GitHub Packages</name>
                    <url>https://maven.pkg.github.com/RoxaMc/maven-packages</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>

          </settings>
          EOF
      - name: Publish package
        run: mvn --batch-mode deploy --settings settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_PACKAGES_PASSWORD }}